```{r setup, echo=FALSE, include=FALSE}
# Tom Hiatt
# 19 December 2013
# Tables and figures to go in the Regional TB report
source('d:/users/hiattt/Dropbox/Code/Surveillance reports/Setup.r')

# Inspired by:
#   
#   http://gforge.se/2014/01/fast-track-publishing-using-knitr-part-ii/


# I can't decide if I pull all this stuff out here or keep it in sequence down below. It seems silly to use markdown and then not incorporate it, doesn't it? Okay I'm putting it here.

# change this to 'postscript' for EPS output.
require(knitr)
opts_chunk$set(dev="png", 
               dev.args=list(type="cairo"),
               dpi=96)

whbc <- c("KHM", "CHN", "LAO", "MNG", "PNG", "PHL", "VNM")

runprofile()
```


Regional TB report `r yr + 1`
========================================================

Abstract 
--------------------------------------------------------
(probably remove this section)

Introduction
--------------------------------------------------------

Tuberculosis in the Western Pacific Region

Burden
--------------------------------------------------------

```{r t.notif.data, echo=FALSE, warning=FALSE}
tableCount <- incCount(tableCount, "t.notif")

# Notification table
tbb <- subset(n, year==yr & g_whoregion=="WPR", select=c('country', 'g_whoregion', 'g_hbc22', 'c_notified', "new_sp", "new_sn", "new_su", "new_ep", "new_oth", "ret_rel", 'c_newinc', "c_ret", "newret_oth", "new_labconf", 'c_new'))

tbb$new.pulm <- .rowsums(tbb[c('new_sp', 'new_sn', 'new_su')])

tbb <- tbb[order(tbb$country),]
names(tbb)[names(tbb)=='country'] <- 'area'

# make aggregate row
tbbr <- aggregate(tbb[4:ncol(tbb)], by=list(area=tbb$g_whoregion), FUN=sum, na.rm=TRUE)


# combine together
tbc <- rbind(tbb[tbb$g_whoregion=='WPR', c(1, 4:ncol(tbb))], tbbr[tbbr$area=='WPR',]) # , tbbh, tbbga

# Fill in data for countries not reporting lab confirmed (see below too)
tbc$new_labconf2 <- ifelse(is.na(tbc$new_labconf), tbc$new_sp, tbc$new_labconf)

# calculate and format vars
tbc$ret_nrel <- tbc$c_ret - tbc$ret_rel
tbc$newpulm_lab_pct <- tbc$new_labconf2 / tbc$new.pulm * 100

for(var in 2:ncol(tbc)){
  tbc[var] <- rounder(tbc[[var]])
}
tbc[is.na(tbc$newpulm_lab_pct), 'newpulm_lab_pct'] <-  "--"
# rename
tbc <- .shortnames(tbc, col='area')

# Add footnote for countries not reporting Lab confirmed (Thailand)
footnote.b <- ifelse(any(is.na(tbc$new_labconf) & !is.na(tbc$new_sp)), paste('(b) LABORATORY CONFIRMED data for', paste(subset(tbc, is.na(new_labconf), 'area'), collapse=', '), 'refer to smear-positive cases only. Data on cases that were laboratory confirmed using other methods were not reported.'), "")
tbc$new_labconf2 <- ifelse(is.na(tbc$new_labconf) & !is.na(tbc$new_sp), glue(tbc$new_sp, "(b)"), tbc$new_labconf2)

tbm <- xtable(tbc[c("area", "c_notified", "new_sp", "new_sn", "new_su", "new_ep", "new_oth", "new_labconf2", "newpulm_lab_pct", "ret_rel", "ret_nrel", "c_newinc")])
digits(tbm) <- 0


```

```{r m.notif.data, echo=FALSE, include=FALSE}

figCount <- incCount(figCount, "m.notif")

# -------------------------------------------------
# Notification data
# -------------------------------------------------

mc <- subset(tb, year==yr & g_whoregion=="WPR", select=c(country, iso2, iso3, g_whoregion, c_tot_newrel_100k))


mc$cat <- cut(round(mc$c_tot_newrel_100k,0), c(0, 10, 50, 100, 200, Inf), c('0–9', '10–49', '50–99', '100–199', '>=200'), right=FALSE)


mc1 <- WHOmap.print(mc, legend.title= "TB cases per \n100 000 population", copyright=FALSE, show=FALSE, zoom="WPR")
```

In `r yr`, national TB control programmes (NTPs) reported `r cnotw <- sum(tb[tb$year==yr & tb$g_whoregion=="WPR", "c_notified"], na.rm=TRUE) ; round(cnotw / 1e6, 1)` million people with TB in the region making up `r round(cnotw / sum(tb[tb$year==yr, "c_notified"], na.rm=TRUE) * 100, 0)`% of the global burden (`r I(pasteLabel("Table", tableCount, "t.notif"))`). Of these cases `r nrw <- sum(tb[tb$year==yr & tb$g_whoregion=="WPR", "tot_newrel"], na.rm=TRUE) ; round(nrw / cnotw * 100, 0)`% were new episodes of TB (either new or relapse cases). Within the region China accounts for `r round(sum(tb[tb$year==yr & tb$iso2=="CN", "tot_newrel"], na.rm=TRUE) / nrw * 100, 0)`% of the caseload with the Philippines and Viet Nam following with `r round(sum(tb[tb$year==yr & tb$iso2=="PH", "tot_newrel"], na.rm=TRUE) / nrw * 100, 0)`% and `r round(sum(tb[tb$year==yr & tb$iso2=="VN", "tot_newrel"], na.rm=TRUE) / nrw * 100, 0)`% respectively. TB notification rates vary in the region with the highest rates found in `r hnr <- .maxplus(tb[tb$year==yr & tb$g_whoregion=="WPR", c("country", "c_tot_newrel_100k")], 'c_tot_newrel_100k', 4) ; paste(paste(hnr[1:3,1], collapse=", "), "and", hnr[4,1])` (`r I(pasteLabel("Figure", figCount, "m.notif"))`). 

<a id="t.notif"></a> 
#### `r I(pasteLabel("Table", tableCount, "t.notif", insLink=FALSE))`. Case notifications, `r yr`.
```{r t.notif, echo=FALSE, results='asis'}

print(tbm, type="html", include.rownames=FALSE, include.colnames=F, html.table.attributes="border=0 rules=rows width=900 cellpadding=5", 
      add.to.row=list(pos=list(0,37), command=c(
"<TR> <TD colspan=2></TD> 
  <TH colspan=7>NEW CASES</TH> 
  <TH colspan=2>RETREATMENT CASES</TH> 
  <TD colspan=1></TD> </TR> 
  <TR> <TD></TD> <TD>TOTAL<br> NOTIFIED</TD> 
  <TD>SMEAR-<br>POSITIVE</TD> 
  <TD>SMEAR-<br>NEGATIVE</TD> 
  <TD>SMEAR NOT DONE</TD>
  <TD>EXTRA-<br>PULMONARY</TD> 
  <TD>CASE TYPE<br> UNKNOWN</TD> 
  <TD>PULMONARY CASES LABORATORY CONFIRMED</TD> 
  <TD>PERCENTAGE OF PULMONARY CASES LABORATORY CONFIRMED</TD>   
  <TD>RELAPSE</TD> 
  <TD>RETREATMENT<br>EXCL. RELAPSE</TD> 
  <TD>NEW AND<br>RELAPSE(a)</TD> 
 </TR>", 
  glue("<TR> <TD colspan=12>Blank cells indicate data not reported. -- indicates values that cannot be calculated.<br>
(a) NEW AND RELAPSE includes cases for which the treatment history is unknown.<br>", footnote.b,"</TD></TR>"))))

```



<a id="m.notif"></a> 
#### `r I(pasteLabel("Figure", figCount, "m.notif", insLink=FALSE))` New and relapse rates per 100 000 population in countries and areas of the Western Pacific Region, `r yr`.
```{r m.notif, echo=FALSE, fig.width=7, height=5}

# -------------------------------------------------
# Notification map
# -------------------------------------------------

mc1
```


```{r agesex.data,  echo=FALSE}
figCount <- incCount(figCount, "f.agesex.bar")
figCount <- incCount(figCount, "f.agesex")

aga <- merge(subset(n.t, year>1999, select=c("iso3", "country", "year", "g_whoregion", "g_hbc22", "new_sp_m04", "new_sp_m514", "new_sp_m014", "new_sp_m1524", "new_sp_m2534", "new_sp_m3544", "new_sp_m4554", "new_sp_m5564", "new_sp_m65", "new_sp_mu", "new_sp_f04", "new_sp_f514", "new_sp_f014", "new_sp_f1524",  "new_sp_f2534", "new_sp_f3544", "new_sp_f4554", "new_sp_f5564", "new_sp_f65", "new_sp_fu")), subset(p, year>1999, select=c("iso3", "country", "year", "e_pop_m04", "e_pop_m514", "e_pop_m014", "e_pop_m1524", "e_pop_m2534", "e_pop_m3544", "e_pop_m4554", "e_pop_m5564", "e_pop_m65", "e_pop_f04", "e_pop_f514", "e_pop_f014", "e_pop_f1524", "e_pop_f2534", "e_pop_f3544", "e_pop_f4554", "e_pop_f5564", "e_pop_f65")))

# Aggregate for region
agb1 <- aggregate(aga[6:ncol(aga)], by=list(year=aga$year, area=aga$g_whoregion), FUN=sum, na.rm=TRUE)

agb1[c('iso3', 'g_hbc22')] <- NA
agb1$g_whoregion <- agb1$area
aga1 <- rename(aga,c('country'='area'))
agb <- rbind(aga1, agb1)

# Calculate rates

agc <- melt(agb, id=1:5)
# agc[c('new', 'type', 'group')] <- str_split_fixed(agc$variable, '_', n=3) # This takes me 25 seconds...it's the '_all' or '_fixed' that's the killer.
agc$type <- str_extract(agc$variable, 'new_sp|pop')
agc$age <- str_replace(agc$variable, "new_sp_|e_pop_", "")
agc$sex <- str_replace(agc$age, '[u]|[0-9]+', "")
agc$age <- str_replace(agc$age, '[f]|[m]', "")

agd <- cast(subset(agc, select= -variable), ...~type)

agd$new_sp_100k <- agd$new_sp / agd$pop * 1e5

# Subset for WPRO
age <- subset(agd, (iso3 %in% whbc | area=="WPR") & age!="u" & age %nin% c("04", "514"))
age$sex <- factor(age$sex, levels=c("m", "f"), labels=c("Male", "Female"))
age$sh.name <- factor(age$iso3, c("KHM", "CHN", "LAO", "MNG", "PNG", "PHL", "VNM", "WPR"), c("Cambodia", "China", "Lao PDR", "Mongolia", "PNG", "Philippines", "Viet Nam", "WPR"))
age[is.na(age$sh.name), 'sh.name'] <- "WPR"
age$age <- factor(age$age, c("014", "1524", "2534", "3544", "4554", "5564", "65"), c("0–14", "15–24", "25–34", "35–44", "45–54", "55–64", "< 64"))

```

<a id="f.agesex.bar"></a> 
#### `r I(pasteLabel("Figure", figCount, "f.agesex.bar", insLink=FALSE))` Smear-positive notification rates by age and sex in the Region and in seven countries with a high burden of TB, `r yr`.
``` {r f.agesex.bar, echo=FALSE, fig.width=11, fig.height=11, warning=FALSE}

p2 <- ggplot(subset(age, year==yr), aes(age, new_sp_100k, fill=sex)) + geom_bar(stat="identity", position="dodge") + facet_wrap(~sh.name, scales='free_y', ncol=2) + theme_few() + scale_fill_brewer('Sex', type="qual", palette=3) + xlab("Age group")

p2 + scale_y_continuous("New smear-positive cases per 100 000")


```

<a id="f.agesex"></a> 
#### `r I(pasteLabel("Figure", figCount, "f.agesex", insLink=FALSE))` Trends of notification rates of new smear-positive TB cases in specific age and sex groups, `r yr`.
``` {r f.agesex, echo=FALSE, warning=FALSE, fig.width=11, fig.height=15}

p1 <- ggplot(age, aes(year, new_sp_100k, color=age)) + geom_line() + facet_grid(sh.name~sex, scales='free_y') + theme_few() + scale_x_continuous("", breaks = pretty_breaks()) + scale_color_brewer("Age group", type="seq", palette=4)

p1 + scale_y_continuous("New smear-positive cases per 100 000")
# p1 + scale_y_log10("New smear-positive cases per 100 000")                                                                                                                                                        
                                                                                                                                                      #function (x) floor(x)); function(n) n[floor(length(n)/5)*1:5+1]
```

As seen in `r I(pasteLabel("Figure", figCount, "f.agesex"))` the trend is evident.



And also as seen in `r I(pasteLabel("Table", tableCount, "t.notif"))` the trend is evident.



Editorial Note
--------------------------------------------------------

Annex
--------------------------------------------------------

The annex will go here.